[env:anchor1]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<Anchor/main_anchor_2.cpp> -<Tag/*>
build_flags = -DANCHOR_ID=1

[env:anchor2]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<Anchor/main_anchor_2.cpp> -<Tag/*>
build_flags = -DANCHOR_ID=2

[env:anchor3]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<Anchor/main_anchor_3.cpp> -<Tag/*>
build_flags = -DANCHOR_ID=3

[env:anchor4]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<Anchor/main_anchor_4.cpp> -<Tag/*>
build_flags = -DANCHOR_ID=4

[env:anchor_listener]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<Anchor/main_anchor1_listener.cpp> -<Tag/*>

[env:tag_broadcast]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<Tag/main_tag_broadcast.cpp> -<Anchor/*>